
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1020, 700)
        Window.setMaximumSize(QtCore.QSize(1020, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window.setWindowIcon(icon)
        Window.setAutoFillBackground(False)
        Window.setStyleSheet("background-color: rgb(0, 37, 64);")
        self.label_3 = QtWidgets.QLabel(Window)
        self.label_3.setGeometry(QtCore.QRect(250, 660, 611, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(185, 99, 36);")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Window)
        self.label.setGeometry(QtCore.QRect(0, 10, 1020, 150))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Window)
        self.label_2.setGeometry(QtCore.QRect(0, 170, 1020, 13))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 431, 309))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Window)
        self.label_5.setGeometry(QtCore.QRect(540, 260, 431, 309))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Window)
        self.label_6.setGeometry(QtCore.QRect(-40, 310, 211, 317))
        self.label_6.setStyleSheet("background-color: none;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Window)
        self.label_7.setGeometry(QtCore.QRect(880, 340, 184, 276))
        self.label_7.setStyleSheet("background-color: none;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Window)
        self.label_8.setGeometry(QtCore.QRect(610, 340, 85, 85))
        self.label_8.setStyleSheet("background-color: none;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Window)
        self.label_9.setGeometry(QtCore.QRect(720, 350, 72, 72))
        self.label_9.setStyleSheet("background-color: none;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Window)
        self.label_10.setGeometry(QtCore.QRect(800, 330, 118, 118))
        self.label_10.setStyleSheet("background-color: none;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Window)
        self.label_11.setGeometry(QtCore.QRect(600, 440, 98, 98))
        self.label_11.setStyleSheet("background-color: none;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Window)
        self.label_12.setGeometry(QtCore.QRect(710, 440, 96, 98))
        self.label_12.setStyleSheet("background-color: none;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Window)
        self.label_13.setGeometry(QtCore.QRect(830, 450, 70, 83))
        self.label_13.setStyleSheet("background-color: none;\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Window)
        self.label_14.setGeometry(QtCore.QRect(620, 300, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: none;\n"
"color: #B96324;")
        self.label_14.setObjectName("label_14")
        self.graduated_btn = QtWidgets.QPushButton(Window)
        self.graduated_btn.setGeometry(QtCore.QRect(112, 107, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.graduated_btn.setFont(font)
        self.graduated_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 11px;")
        self.graduated_btn.setObjectName("graduated_btn")
        self.students_btn = QtWidgets.QPushButton(Window)
        self.students_btn.setGeometry(QtCore.QRect(112, 69, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.students_btn.setFont(font)
        self.students_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 11px;")
        self.students_btn.setObjectName("students_btn")
        self.lecturer_btn = QtWidgets.QPushButton(Window)
        self.lecturer_btn.setGeometry(QtCore.QRect(112, 30, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lecturer_btn.setFont(font)
        self.lecturer_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 11px;")
        self.lecturer_btn.setObjectName("lecturer_btn")
        self.heads_btn = QtWidgets.QPushButton(Window)
        self.heads_btn.setGeometry(QtCore.QRect(685, 107, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.heads_btn.setFont(font)
        self.heads_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 11px;")
        self.heads_btn.setObjectName("heads_btn")
        self.courses_btn = QtWidgets.QPushButton(Window)
        self.courses_btn.setGeometry(QtCore.QRect(685, 69, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.courses_btn.setFont(font)
        self.courses_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 11px;")
        self.courses_btn.setObjectName("courses_btn")
        self.subject_chois_btn = QtWidgets.QPushButton(Window)
        self.subject_chois_btn.setGeometry(QtCore.QRect(685, 30, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.subject_chois_btn.setFont(font)
        self.subject_chois_btn.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 11px;")
        self.subject_chois_btn.setObjectName("subject_chois_btn")
        self.add_student_btn = QtWidgets.QPushButton(Window)
        self.add_student_btn.setGeometry(QtCore.QRect(150, 370, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_student_btn.setFont(font)
        self.add_student_btn.setStyleSheet("background-color: rgb(239, 170, 79);\n"
"border-radius: 11px;\n"
"color: rgb(255, 255, 255);")
        self.add_student_btn.setObjectName("add_student_btn")
        self.add_lecturer_btn = QtWidgets.QPushButton(Window)
        self.add_lecturer_btn.setGeometry(QtCore.QRect(150, 410, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_lecturer_btn.setFont(font)
        self.add_lecturer_btn.setStyleSheet("background-color: rgb(239, 170, 79);\n"
"border-radius: 11px;\n"
"color: rgb(255, 255, 255);")
        self.add_lecturer_btn.setObjectName("add_lecturer_btn")
        self.add_course_btn = QtWidgets.QPushButton(Window)
        self.add_course_btn.setGeometry(QtCore.QRect(150, 450, 224, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_course_btn.setFont(font)
        self.add_course_btn.setStyleSheet("background-color: rgb(239, 170, 79);\n"
"border-radius: 11px;\n"
"color: rgb(255, 255, 255);")
        self.add_course_btn.setObjectName("add_course_btn")

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "უნი. მართვის სისტემა"))
        self.label_3.setText(_translate("Window", "© სულხან კვერნაძის უნივერსიტეტი - ყველა უფლება დაცულია."))
        self.label.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/Group 22.png\"/></p></body></html>"))
        self.label_2.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/Line 4.png\"/></p></body></html>"))
        self.label_4.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/div1.png\"/></p></body></html>"))
        self.label_5.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/div1.png\"/></p></body></html>"))
        self.label_6.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/kverna1.png\"/></p></body></html>"))
        self.label_7.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/kverna3.png\"/></p></body></html>"))
        self.label_8.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/harvar 1.png\"/></p></body></html>"))
        self.label_9.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/GTU 1.png\"/></p></body></html>"))
        self.label_10.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/lomebi 1.png\"/></p></body></html>"))
        self.label_11.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/stanford 1.png\"/></p></body></html>"))
        self.label_12.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/tavisufali 1.png\"/></p></body></html>"))
        self.label_13.setText(_translate("Window", "<html><head/><body><p><img src=\":/logo/oxford 1.png\"/></p></body></html>"))
        self.label_14.setText(_translate("Window", "პარტნიორი უნივერსიტეტები"))
        self.graduated_btn.setText(_translate("Window", "კურსდამთავრებულები"))
        self.students_btn.setText(_translate("Window", "სტუდენტები"))
        self.lecturer_btn.setText(_translate("Window", "ლექტორები"))
        self.heads_btn.setText(_translate("Window", "დამფუძვნებლები"))
        self.courses_btn.setText(_translate("Window", "კურსები"))
        self.subject_chois_btn.setText(_translate("Window", "საგნის არჩევა"))
        self.add_student_btn.setText(_translate("Window", "სტუდ დამ/გან/წაშ"))
        self.add_lecturer_btn.setText(_translate("Window", "ლექტ დამ/გან/წაშ"))
        self.add_course_btn.setText(_translate("Window", "კურსის დამ/გან/წაშ"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QDialog()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
